config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :agents, only: [ :index, :new, :create ], shallow: true
  end

  resources :agents, only: [ :show, :edit, :update, :destroy ]

  resources :factions
  resources :systems

  get "dashboard/index"

  resource :session
  resources :passwords, param: :token
  resource :registrations, only: [ :new, :create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/agent.rb
class Agent < ApplicationRecord
  belongs_to :user
  belongs_to :faction
  has_one :headquarters
  has_many :ships
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  belongs_to :ship
  has_many   :inventory_items,
    class_name: "CargoInventoryItem",
    dependent: :destroy
end

app/models/cooldown.rb
class Cooldown < ApplicationRecord
  belongs_to :ship
end

app/models/crew.rb
class Crew < ApplicationRecord
  belongs_to :ship

  # enum rotation: {
  #   STRICT:   "STRICT",
  #   RELAXED:  "RELAXED"
  # }

  validates :current, :required, :capacity, :rotation,
    :morale, :wages, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/engine.rb
class Engine < ApplicationRecord
  belongs_to :ship
  has_one    :requirements,
    class_name: "EngineRequirement",
    dependent: :destroy
end

app/models/faction.rb
class Faction < ApplicationRecord
  has_one :headquarters
end

app/models/frame.rb
class Frame < ApplicationRecord
  belongs_to :ship
  has_one    :requirements,
    class_name: "FrameRequirement",
    dependent: :destroy
end

app/models/fuel.rb
class Fuel < ApplicationRecord
  belongs_to :ship
  has_many :fuel_consumptions
end

app/models/mount.rb
class Mount < ApplicationRecord
  belongs_to :ship
  has_one    :requirements,
    class_name: "MountRequirement",
    dependent: :destroy
  has_many   :mount_deposits,
    dependent: :destroy
end

app/models/mount_deposit.rb
class MountDeposit < ApplicationRecord
  belongs_to :mount
end

app/models/nav.rb
class Nav < ApplicationRecord
  belongs_to :ship
  has_one    :route, dependent: :destroy

  # enum status: {
  #   in_transit: "in_transit",
  #   docked:     "docked",
  #   in_orbit:   "in_orbit"
  # }
  #
  # enum flight_mode: {
  #   cruise: "cruise",
  #   stealth: "stealth",
  #   burn:    "burn"
  # }

  validates :system_symbol, :waypoint_symbol, :status, :flight_mode, presence: true
end

app/models/reactor.rb
class Reactor < ApplicationRecord
  belongs_to :ship
  has_one    :requirements,
    class_name: "ReactorRequirement",
    dependent: :destroy
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :ship

  # enum role: {
  #   FABRICATOR: "FABRICATOR"
  # }

  validates :name, :faction_symbol, :role, presence: true
end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :nav

  validates :departure_time, :arrival_time, presence: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/ship.rb
class Ship < ApplicationRecord
  has_one  :registration,   dependent: :destroy
  has_one  :nav,            dependent: :destroy
  has_one  :crew,           dependent: :destroy
  has_one  :frame,          dependent: :destroy
  has_one  :reactor,        dependent: :destroy
  has_one  :engine,         dependent: :destroy
  has_one  :cooldown,       dependent: :destroy

  has_many :ship_modules,        dependent: :destroy
  has_many :module_requirements, through: :ship_modules
  has_many :mounts,              dependent: :destroy
  has_many :mount_deposits,      through: :mounts
  has_one  :cargo,               dependent: :destroy
  has_many :cargo_inventory_items, through: :cargo
  has_one  :fuel,                dependent: :destroy
  has_many :fuel_consumptions,   through: :fuel

  validates :symbol, presence: true, uniqueness: true
end

app/models/ship_module.rb
class ShipModule < ApplicationRecord
  belongs_to :ship
end

app/models/system.rb
class System < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :agents

  validates :email_address, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/views/layouts/_flash.html.erb
<%# layouts/_flash.html.erb %>
<div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade show w-50 mx-auto" role="alert">
  <%= message %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_flashes.html.erb
<% flash.each do |type, messages| %>
  <% Array(messages).each do |message| %>
    <%= render "layouts/flash", type: type, message: message %>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class: "navbar-brand #{ 'active' if current_page?(root_path) }" %>
    <button class="navbar-toggler" type="button"
                                   data-bs-toggle="collapse"
                                   data-bs-target="#navbarNav"
                                   aria-controls="navbarNav"
                                   aria-expanded="false"
                                   aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <% if Current.user.present? %>
        <ul class="navbar-nav mx-auto">
          <li class="nav-item">
            <%= link_to 'Dashboard', root_path,
              class: "nav-link #{ 'active' if current_page?(root_path) }" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Agents', user_agents_path(Current.user),
              class: "nav-link #{ 'active' if controller_name == 'agents' }" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Factions', factions_path,
              class: "nav-link #{ 'active' if controller_name == 'factions' }" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Systems', systems_path,
              class: "nav-link #{ 'active' if controller_name == 'systems' }" %>
          </li>
        </ul>
      <% end %>

      <ul class="navbar-nav ms-auto">
        <% if Current.user.present? %>
          <li class="nav-item">
            <%= button_to 'Log Out', session_path,
              method: :delete,
              class: "btn btn-outline-danger nav-link #{ 'active' if current_page?(session_path) }" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_session_path,
              class: "nav-link #{ 'active' if current_page?(new_session_path) }" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_registrations_path,
              class: "nav-link #{ 'active' if current_page?(new_registrations_path) }" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Space Traders" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container my-4">

      <%= render "layouts/flashes" %>

      <%= yield %>

    </div>
  </body>
</html>